version: '3'
services:
  the-dark-app-db-local:
    image: postgres:latest
    volumes:
      - ./dark_app_db_local:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  the-dark-app-local:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src/main/resources/secret.properties:/secret.properties:rw
    environment:
      - DB_HOST=the-dark-app-db-local
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - "8182:8080"
    depends_on:
      the-dark-app-db-local:
        condition: service_healthy
