version: '3'
services:
  the-dark-app-db:
    image: postgres:latest
    volumes:
      - ./dark_app_db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=$DB_NAME
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  the-dark-app:
    build:
      dockerfile: Dockerfile
    environment:
      - DB_HOST=the-dark-app-db
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - "8080:8080"
    depends_on:
      the-dark-app-db:
        condition: service_healthy
